name: ecom_shop
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

scripts:
  run: flutter run
  build:
    android: flutter build apk --split-per-abi
    ios: flutter build ios

dependencies:
  flutter:
    sdk: flutter

  # utility packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.2+1
  url_launcher: ^6.2.1
  flutter_native_splash: ^2.3.5
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1

  # icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # state management
  get: ^4.6.6
  get_storage: ^2.1.1
  firebase_core: ^2.25.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/content/
    - assets/icons/categories/
    - assets/icons/
    - assets/logos/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800